name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: fmt check
        run: make fmtcheck

      -
        name: Test GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --skip-validate --rm-dist
